### ISSUE TITLE
Add connection via Bot-Account

### ISSUE THREAD

**Issue by Develeon64** [build-with-me/vscode-twitch-themer#156]
This is just great, but one thing I'm missing.
I'm using a custom Bot-Account for my other bots and it would be nice, if I could connect this Plugin to it, too, instead of connecting it with my Stream-Account.

**Comment by MichaelJolley** [comment]
Thanks for the idea @Develeon64! I would benefit from this as well. Currently, we're opening a browser to authenticate for joining chat and use those same credentials for sending messages.

@parithon perhaps we should have the authentication process be used only for listening/sending/whispering and have a separate channel settings. So people can enter a channel name in the settings and we'll join that channel as the authenticated account.

@all-contributors please add @Develeon64 for ideas.

**Comment by parithon** [comment]
@MichaelJolley I'm not following your suggestion, sorry.

As for allowing people to login with another account other than their broadcast account, there is an optional URL parameter that forces a user to reverify their login: `force_verify`. The big downside? VSCode opens the URL in the default browser and if you're already logged into your broadcaster account and choose to 'switch' accounts, then you'll be logged out of Twitch first before logging back in requiring you to re-log once more to use your primary account.

**Comment by MichaelJolley** [comment]
We're now using an auth provider extension to control logging in to Twitch. Unfortunately, this means the account you authenticate as must be the streamers account. 

We _can_ still implement this, but we'll need to add a setting of "what channel to join?" Then we could default joining the logged in user unless that setting is provided.

I'm in a similar situation. I currently authenticate as BaldBeardedBuilder, but it would be nice to authenticate as B3_Bot, but then specify it should join the BaldBeardedBuilder channel.

**Comment by MichaelJolley** [comment]
Thanks for this feature request @Develeon64. Now that I'm back at it, it was a pretty small lift. By default, the extension will join the channel you are authenticated with (in this case your bot.) However, there is a new setting that allows you to enter the name of the channel the extension should be listening to. Enjoy!
